image: gitlab-registry.cern.ch/linuxsupport/alma9-base:latest

before_script:
  - dnf install -y epel-release dnf-plugins-core
  - dnf config-manager --set-enabled crb
  - dnf install -y xrootd-client
  - echo "$X509_PROXY_B64" | base64 -d > "$X509_USER_PROXY"
  - chmod 600 "$X509_USER_PROXY"

pages:
  stage: deploy
  variables:
    EOS_MGM_URL: root://eosuser.cern.ch
    EOS_PATH: /eos/user/m/mccauley/masterclass2026-files/ig
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - mkdir -p public
    - mkdir -p public/css
    - mkdir -p public/geometry/gltf
    - mkdir -p public/geometry/obj
    - mkdir -p public/fonts
    - mkdir -p public/graphics
    - mkdir -p public/js/lib
    - mkdir -p public/webfonts
    - mkdir -p public/masterclass
    - cp index.html public/index.html
    - cp css/*.css public/css
    - cp geometry/gltf/*.* public/geometry/gltf
    - cp geometry/obj/*.* public/geometry/obj
    - cp fonts/*.*  public/fonts
    - cp graphics/*.* public/graphics
    - cp js/*.js public/js
    - cp js/lib/*.js public/js/lib
    - cp webfonts/*.* public/webfonts
    - echo $EOS_MGM_URL/$EOS_PATH
    - export X509_USER_PROXY
    - xrdcp $EOS_MGM_URL/$EOS_PATH/masterclass_1.ig public/masterclass
  artifacts:
    paths:
      - public
  rules:
      - if: '$CI_COMMIT_BRANCH == "masterclass26"'