image: gitlab-registry.cern.ch/linuxsupport/alma9-base:latest

before_script:
  - dnf install -y epel-release dnf-plugins-core
  - dnf config-manager --set-enabled crb
  - dnf install -y xrootd-client

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - mkdir -p public
    - mkdir -p public/css
    - mkdir -p public/geometry/gltf
    - mkdir -p public/geometry/obj
    - mkdir -p public/fonts
    - mkdir -p public/graphics
    - mkdir -p public/js/lib
    - mkdir -p public/webfonts
    - mkdir -p public/masterclass
    - cp index.html public/index.html
    - cp css/*.css public/css
    - cp geometry/gltf/*.* public/geometry/gltf
    - cp geometry/obj/*.* public/geometry/obj
    - cp fonts/*.*  public/fonts
    - cp graphics/*.* public/graphics
    - cp js/*.js public/js
    - cp js/lib/*.js public/js/lib
    - cp webfonts/*.* public/webfonts
    - xrdcp "root://eosuser.cern.ch//eos/user/m/mccauley/masterclass2026-files/ig/masterclass_1.ig?authz=$EOS_TOKEN" public/masterclass
  artifacts:
    paths:
      - public
  rules:
      - if: '$CI_COMMIT_BRANCH == "masterclass26"'